### ISSUE TITLE
用户的事件函数 panic 导致进程起不来的优化处理

### ISSUE THREAD

**Issue by kirinzhong** [bytedance/dddfirework#2]
当前如果用户事件函数 panic，会触发事件失败策略，反复消费该事件，引起反复 panic，然后进程无法重启，框架应该考虑优化的方案

**Comment by qiankunli** [comment]
感觉上
1.  用户事件函数panic 是可能出现的，框架应该recover，不能影响程序运行，将panic 视为处理失败，打错误日志等
2. 一般还不错的业务系统，会有日志采集报警系统，通过报警引起用户干预

如果recover 了panic，进程为何会无法重启呢？

**Comment by kirinzhong** [comment]
主要是看职责，panic 如果是业务错误，应该由业务明确感知并且解决，底层框架不应该兜住，也不应该假定业务一定会有日志监控系统，如果业务不做是不是这个 panic 就不被发现了？
同时框架需要有一定的鲁棒性，保障自己的运行，所以结合到一起，只要处理对于重试无望的事件做丢弃处理就行了。

**Comment by yeehomfoo** [comment]
已优化 #18
