### ISSUE TITLE
Rename mysql executor to sql executor

### ISSUE THREAD

**Issue by ealyn** [bytedance/dddfirework#5]
Mysql executor receive a gorm.DB, and gorm.DB have many drivers, e.g. postgres sqlite.
So `sql` is more proper?
https://github.com/bytedance/dddfirework/blob/3ddc321a1779a4a37aacb6ab2d02a542b9176a83/executor/mysql/executor.go#L127-L127

**Comment by kirinzhong** [comment]
okay

**Comment by ealyn** [comment]
executor transaction no work will in sqlite.
